/**
 * This file contains the completion function for the general agent.
 *
 * Agent Action Function needs to follow the following criteria:
 * 1. It should use its respective system prompt
 * 2. It should deduct tokens from the users account (IMPORTANT)
 * 3. It should return the response like { success: true, message: "response", totalTokens: 100 } if everything is correct
 * 4. It should return the response line {success: false, message "error message"} if something goes wrong
 */

"use server";

import { z } from "zod";
import OpenAITextCompletion from "../openai-completion";
import { ConversationWithOutSystemPromptSchema } from "@/server/validation/openai/openai-messages";
import { PromptFactory } from "@/server/prompts/prompt-factory";
import DeductTokenFromUserAccountForMessage from "../../usage/token-deduction";
import TurnRepo from "@/server/database/repositories/turn";
import VocabAgentSuggestionRepo from "@/server/database/repositories/vocab-agent-suggestion";
import validateOrCreateConversation from "./validate-conversation-id";
import VocabAgentCompletion from "../vocab/completion";
import UserRepo from "@/server/database/repositories/user";
import VocabularyBucketRepo from "@/server/database/repositories/vocabulary-bucket";
import VocabularyRepo from "@/server/database/repositories/vocabulary";

export default async function GeneralAgentCompletion(
  userId: string,
  messages: z.infer<typeof ConversationWithOutSystemPromptSchema>,
  conversationId?: string,
  requestNewConversation?: boolean,
  useVocabAgent?: boolean
) {
  try {
    // TODO: check if user have tokens to generate the response
    // Validate the conversation and get the current conversationId or create a new one if needed
    let conversation = await validateOrCreateConversation(
      userId,
      messages,
      conversationId,
      requestNewConversation
    );
    let conversationIdCurrent = conversation.id;
    let system_prompt = PromptFactory.getDefaultSystemPrompt();
    const [reply, totalTokens] = await OpenAITextCompletion(
      messages,
      system_prompt,
    );
    if (!reply || !totalTokens) {
      throw new Error(
        "Failed to generate a response or calculate total tokens."
      );
    }

    // Record the turn in the database
    const turn = await TurnRepo.CreateTurnInDB(
      userId,
      conversationIdCurrent,
      messages[messages.length - 1].content,
      reply + "",
      totalTokens as number
    );
    if (!turn) {
      throw new Error("Failed to record the turn in the database.");
    }

    // Deduct tokens from the user's account
    await DeductTokenFromUserAccountForMessage(
      userId,
      turn.id,
      parseInt(totalTokens + "", 10)
    );

    // TODO: use api call maybe?
    // Create a vocabulary bucket in the database if it does not exist in the user tables autoGeneratedBucketId.
    let user = await UserRepo.findUserById(userId);
    if (user?.autoGeneratedBucketId === null) {

      // create a new bucket
      const newBucket = await VocabularyBucketRepo.createVocabularyBucket(userId, "Auto Generated Bucket");
      // update the user table with the new bucket id
      user = await UserRepo.updateAutoGeneratedBucketId(userId, newBucket.id);
    }



    if (useVocabAgent) {
      // Call the completion function for the VocabAgent
      const vocabData = await VocabAgentCompletion(messages);

      // Check if the completion function was successful
      if (!vocabData.success)
        throw new Error(vocabData.message as string | "Vocabulary search error.");

      // add to the database VocabAgentSuggestion
      const vocabAgentSuggestion = await VocabAgentSuggestionRepo.createVocabAgentSuggestion(
        turn.id,
        vocabData.totalTokens as number,
        vocabData.enhanced_text as string,
        vocabData.words,
        vocabData.phrases,
      );

      if (!vocabAgentSuggestion) {
        throw new Error("Failed to record the VocabAgentSuggestion in the database.");
      }

      // create the vocabularies in the database with words
      for (const [key, value] of Object.entries(vocabData.words)) {
        await VocabularyRepo.createVocabulary(
          user?.autoGeneratedBucketId as string,
          value as string,
          "word",
          "example sentence"
        );
      }

      // create the vocabulary in the database with phrases
      for (const [key, value] of Object.entries(vocabData.phrases)) {
        await VocabularyRepo.createVocabulary(
          user?.autoGeneratedBucketId as string,
          value as string,
          "phrase",
          "example sentence"
        );
      }

      return {
        success: true,
        message: reply,
        totalTokens: totalTokens,
        conversationId: conversationIdCurrent,
        title: conversation.title,
        createdAt: conversation.createdAt,
        vocab_agent_response: vocabData,
      }
    }


    return {
      success: true,
      message: reply,
      totalTokens: totalTokens,
      conversationId: conversationIdCurrent,
      title: conversation.title,
      createdAt: conversation.createdAt,
    };
  } catch (error) {
    return {
      success: false,
      message: (error as Error).message,
    };
  }
}
