"use server";

import { auth } from "@/server/authentication/auth";
import React from "react";
import FlashCards from "./_components/flashcards";
import Buckets from "./_components/buckets";
import UserRepo from "@/server/database/repositories/user";

export default async function AppPage({
  params,
}: {
  params: { conversationId: string };
}) {
  // const conversationId = params.conversationId as string;
  const session = await auth();
  if (!session || !session.user) return null;

  // console.log('session', session.user);
  
  let user = await UserRepo.findUserById(session.user.userId);
  

  return <Buckets autoGeneratedBucketId={user?.autoGeneratedBucketId}/>;
}
